# Generated by Django 6.0.4 on 2026-06-03 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reminder_date', models.DateField()),
                ('reminder_time', models.TimeField()),
                ('visibility', models.CharField(choices=[('shared', 'Shared'), ('private', 'Private')], default='shared', max_length=20)),
                ('recurring', models.CharField(choices=[('one_time', 'One time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='one_time', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reminders', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='authentication.family')),
                ('owner', models.ForeignKey(blank=True, help_text='Null means Family reminder', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_completed', 'reminder_date', 'reminder_time'],
            },
        ),
    ]
